services:
- type: web
  name: my-react-app
  buildCommand: yarn build
  startCommand: yarn start
  env:
    NODE_ENV: production
  port: 3000
  healthCheckPath: /health

routes:
- path: /*
  service: my-react-app
